language: python
sudo: false
dist: bionic
cache:
  pip: true
  directories:
  - eggs
  - downloads
jobs:
  fast_finish: true
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
install:
  - pip install -r requirements-${PLONE_VERSION}.txt
  - buildout -Nc buildout-${PLONE_VERSION}.cfg buildout:download-cache=downloads
script:
  - bin/test
